name: Sayanee
description: Internet of Things, Minimalism and Space
author: Sayanee
email: sayanee@gmail.com
tags: iot, software, hardware, web, internet, open source, minamlism, non-materialism, outer space, space, cosmology, astronomy, astrophysics
feed: http://feeds.feedburner.com/sayanee
destination: ./_publish
permalink: /:title
exclude: ['sass', 'node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'automation']
markdown: redcarpet
url: http://localhost:4000
